runtime: python
env: flex
entrypoint: gunicorn -b :$PORT app:app

runtime_config:
  operating_system: ubuntu22

instance_class: F4_1G

automatic_scaling:
  max_concurrent_requests: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
